### ISSUE TITLE
Error: GraphQL error: no mutations exist

### ISSUE THREAD

**Issue by jayqui** [electionscience/Booth#3]
Hi @fsargent, I have the project loaded up and can log in with Google Auth0. However, once the app loads, I'm getting the error `Error: GraphQL error: no mutations exist`. 

![image](https://user-images.githubusercontent.com/10286362/63144884-ebebfb00-bfa9-11e9-9351-e09a84cbdf18.png)

Surely I misunderstood something about the setup instructions. What am I missing?

**Comment by fsargent** [comment]
Hiya Jay,
Thanks! Really excited you've gotten this far. This isn't yet a working client. The client that's in there is a fork of a todo-example for the framework to be used. I'm not sure if we should start off with this framework or start from scratch. 
Check out the DB and schema here: https://ces-voting.herokuapp.com/console
Password: `ElectionScienceBurrito`
